apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: health-tracking
data:
  default.conf: |
    server {
        listen 80;
        server_name vuthanhdat04.id.vn;

        # 1. Nếu người dùng vào trang web (Frontend)
        # Nó sẽ chuyển vào service tên là "client" mà bạn đã deploy
        location / {
            proxy_pass http://client.health-tracking.svc.cluster.local:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 2. Nếu người dùng gọi API (Backend)
        # Ví dụ: /api/users/login -> chuyển vào api-gateway
        location /api/ {
            # Chuyển vào service api-gateway
            proxy_pass http://api-gateway.health-tracking.svc.cluster.local:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }