apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: health-tracking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: acrhealth.azurecr.io/api-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http-web
          env:
            - name: PORT
              value: "8080"

            # ENV cho backend service
            - name: USER_SERVICE_URL
              value: "http://user-service.health-tracking.svc.cluster.local:4001/api/users"
            - name: ACTIVITY_SERVICE_URL
              value: "http://activity-service.health-tracking.svc.cluster.local:4002/api/activities"
            - name: METRIC_SERVICE_URL
              value: "http://health-metrics-service.health-tracking.svc.cluster.local:4003/api/metrics"
            - name: PROGRESS_SERVICE_URL
              value: "http://progress-service.health-tracking.svc.cluster.local:4004/api/progress"

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: health-tracking
  labels:
    app: api-gateway
    release: monitoring-stack
spec:
  selector:
    app: api-gateway
  type: ClusterIP
  ports:
    - name: http-web
      port: 8080
      targetPort: 8080
