apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: health-tracking
spec:
  type: LoadBalancer
  selector:
    app: api-gateway     # phải khớp với label trong Deployment
  ports:
    - name: http
      port: 8080         # port mà client sẽ gọi tới
      targetPort: 8080   # containerPort trong Deployment api-gateway
