apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: health-tracking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: acrhealth.azurecr.io/api-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http-web
          env:
            - name: PORT
              value: "8080"

            # ENV cho backend service
            - name: USER_SERVICE_URL
              value: "http://user-service.health-tracking.svc.cluster.local:4001/api/users"
            - name: ACTIVITY_SERVICE_URL
              value: "http://activity-service.health-tracking.svc.cluster.local:4002/api/activities"
            - name: METRIC_SERVICE_URL
              value: "http://health-metrics-service.health-tracking.svc.cluster.local:4003/api/metrics"
            - name: PROGRESS_SERVICE_URL
              value: "http://progress-service.health-tracking.svc.cluster.local:4004/api/progress"
          livenessProbe:              # Kiểm tra xem Pod có còn sống không
            httpGet:
              path: /health           # Endpoint health check
              port: 8080
            initialDelaySeconds: 30   # Đợi 30s sau khi start mới check
            periodSeconds: 10         # Check mỗi 10s
          readinessProbe:             # Kiểm tra xem Pod đã sẵn sàng nhận traffic chưa
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          # ---------------------------------------------------
          resources:
            requests:
              cpu: "100m"     
              memory: "128Mi" 
            limits:
              cpu: "300m"     
              memory: "256Mi"
---
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: health-tracking
  labels:
    app: api-gateway
    release: monitoring-stack
spec:
  selector:
    app: api-gateway
  type: ClusterIP
  ports:
    - name: http-web
      port: 8080
      targetPort: 8080
