apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: client-monitor
  namespace: monitoring
  labels:
    release: monitoring-stack
spec:
  selector:
    matchLabels:
      app: client
  namespaceSelector:
    matchNames:
      - health-tracking
  endpoints:
  - port: metrics   # Trùng với tên port 9113 
    path: /metrics  # Exporter dùng đường dẫn khác với backend
    interval: 15s