apiVersion: apps/v1
kind: Deployment
metadata:
  name: progress-service
  namespace: health-tracking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: progress-service
  template:
    metadata:
      labels:
        app: progress-service
    spec:
      containers:
        - name: progress-service
          image: acrhealth.azurecr.io/progress-service:${TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 4004        # đúng với app.listen(...)
          env:
            - name: PORT
              value: "4004"
            # ĐỔI TÊN BIẾN CHO KHỚP CODE (VD: DB_URI, MONGO_URI, ...)
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret    # Secret tạo ở bước trước
                  key: DB_URI
            - name: RABBITMQ_URL  # Tên biến này phải khớp với code của bạn
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-config        # Tên secret tạo ở Bước 2
                  key: RABBITMQ_CONNECTION_STRING
---
apiVersion: v1
kind: Service
metadata:
  name: progress-service
  namespace: health-tracking
spec:
  selector:
    app: progress-service
  ports:
    - port: 4004
      targetPort: 4004
  type: ClusterIP
