apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: health-tracking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: acrhealth.azurecr.io/user-service:${TAG}
          imagePullPolicy: Always
          ports:
            - containerPort: 4001        # đúng với app.listen(...)
          env:
            - name: PORT
              value: "4001"
            # ĐỔI TÊN BIẾN CHO KHỚP CODE (VD: DB_URI, MONGO_URI, ...)
            - name: DB_URI
              value: "mongodb+srv://n22dccn063_db_user:Quang98912004@cluster0.mqqf8x4.mongodb.net/health-tracker?appName=Cluster0"
            - name: RABBITMQ_URL  # Tên biến này phải khớp với code của bạn
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-config        # Tên secret tạo ở Bước 2
                  key: RABBITMQ_CONNECTION_STRING
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: health-tracking
spec:
  selector:
    app: user-service
  ports:
    - port: 4001
      targetPort: 4001
  type: ClusterIP
