apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: health-tracking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: acrhealth.azurecr.io/user-service:IMAGE_TAG
        ports:
        - containerPort: 4001
        env:
        - name: DB_URI
          valueFrom:
            secretKeyRef:
              name: health-env-secret
              key: USER_DB_URI
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: health-env-secret
              key: USER_NODE_ENV
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: health-env-secret
              key: USER_PORT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: health-env-secret
              key: USER_JWT_SECRET
