apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-service
  namespace: health-tracking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activity-service
  template:
    metadata:
      labels:
        app: activity-service
    spec:
      containers:
      - name: activity-service
        image: acrhealth.azurecr.io/activity-service:IMAGE_TAG
        ports:
        - containerPort: 4002
        env:
        - name: DB_URI
          valueFrom:
            secretKeyRef:
              name: health-env-secret
              key: ACTIVITY_DB_URI
        - name: NODE_ENV
          valueFrom:
            secretKeyRef:
              name: health-env-secret
              key: ACTIVITY_NODE_ENV
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: health-env-secret
              key: ACTIVITY_PORT
