apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: health-tracking
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: acrhealth.azurecr.io/api-gateway:__IMAGE_TAG__
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          valueFrom:
            secretKeyRef:
              name: health-env-secret
              key: GATEWAY_PORT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: health-env-secret
              key: GATEWAY_JWT_SECRET
        - name: USER_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: health-env-secret
              key: USER_SERVICE_URL
        - name: ACTIVITY_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: health-env-secret
              key: ACTIVITY_SERVICE_URL
        - name: METRIC_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: health-env-secret
              key: METRIC_SERVICE_URL
        - name: PROGRESS_SERVICE_URL
          valueFrom:
            secretKeyRef:
              name: health-env-secret
              key: PROGRESS_SERVICE_URL
