apiVersion: v1
kind: Service
metadata:
  name: health-metrics-service
  namespace: health-tracking
spec:
  selector:
    app: health-metrics-service
  ports:
    - port: 4003
      targetPort: 4003
  type: ClusterIP
