apiVersion: v1
kind: Service
metadata:
  name: activity-service
  namespace: health-tracking
spec:
  selector:
    app: activity-service
  ports:
    - port: 4002
      targetPort: 4002
  type: ClusterIP